user:
  avatar:
    sizes:
      default: 200
      small: 100
      large: 500
image:
  max_capacity: 5 #MB
per_page: 4
min_player_of_team: 5
team:
  logo_size_title: "70x70"
  logo_size_left: "50x50"
