admin:
  size: "70x70"
  url: "assets/images/avatar.jpg"
news:
  per_page: 2
image:
  max_capacity: 5 #MB
teams:
  per_page: 1
players:
  per_page: 2
per_page: 4
min_player_of_team: 2
team:
  logo_size_title: "70x70"
  logo_size_left: "50x50"
league_season:
  min_team_of_league: 4
number_of_year: 10
match:
  ball_size: "70x70"
  ball_img: "league-icon.png"
