admin:
  size: "50x50"
  url: "default_avatar.jpg"
news:
  per_page: 2
  preview_represent_image_size: "500x300"
image:
  max_capacity: 5 #MB
teams:
  per_page: 3
players:
  per_page: 3
  preview_avatar_size: "200x200"
per_page: 4
min_player_of_team: 2
team:
  logo_size_title: "70x70"
  logo_size_left: "50x50"
  preview_logo_size: "200x200"
league_season:
  min_team_of_league: 4
number_of_year: 10
match:
  ball_size: "70x70"
  ball_img: "league-icon.png"
  duration: 1
users:
  per_page: 5
  avatar_size: "200x200"
  avt_default: "default_avatar.jpg"
  preview_avatar_size: "200x200"
activity:
  logo_team: "30x30"
  per_page: 5
country:
  per_page: 4
  size_tiny: "40x20"
  size_small: "60x30"
league_seasons:
  per_page: 3
leagues:
  per_page: 2
