admin:
  size: "50x50"
  url: "default_avatar.jpg"
news:
  per_page: 10
  preview_represent_image_size: "700x400"
  preview_newest: 5
  preview_newest_in_types: 6
  per_page_user: 5
  hot_news: 10
  hot_days_ago: 7
image:
  max_capacity: 5 #MB
  coin: "coin.png"
  coin_size: "30x30"
teams:
  per_page: 3
players:
  per_page: 3
  preview_avatar_size: "200x200"
per_page: 4
min_player_of_team: 2
team:
  logo_size_tiny: "30x30"
  logo_size_title: "70x70"
  logo_size_left: "50x50"
  preview_logo_size: "200x200"
league_season:
  min_team_of_league: 4
number_of_year: 10
match:
  ball_size: "70x70"
  ball_img: "league-icon.png"
  duration: 5
  minute_of_match: 120
users:
  per_page: 5
  avatar_size: "200x200"
  avt_default: "default_avatar.jpg"
  preview_avatar_size: "200x200"
activity:
  logo_team: "30x30"
  per_page: 5
country:
  per_page: 4
  size_tiny: "40x20"
  size_small: "60x30"
  preview_flag_size: "300x150"
league_seasons:
  per_page: 3
leagues:
  per_page: 2
banner_image_height: 150
format:
  time: "%I:%M %p"
  date_time: "%d-%m-%Y %I:%M %p"
  date: "%d-%m-%Y"
  time24: "%H : %M"
  date_input: "%Y-%m-%d"
user_bets:
  per_page: 5
